"""empty message

Revision ID: 63d0e088f8f3
Revises: 
Create Date: 2023-03-09 16:10:18.162238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d0e088f8f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_product',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('amazon_review',
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['amazon_product.pid'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amazon_review')
    op.drop_table('amazon_product')
    # ### end Alembic commands ###
